### ISSUE TITLE
Update Workflows

### ISSUE THREAD

**Issue by StormFX** [SFX-WoW/shared#1]
Update all repositories to use reusable workflows.

- [x] SFX-WoW/AceGUI-3.0_SFX-Widgets#40
- [x] SFX-WoW/Masque#154
- [x] SFX-WoW/Masque_Apathy#19
- [x] SFX-WoW/Masque_Caith#23
- [x] SFX-WoW/Masque_Cirque#16
- [x] SFX-WoW/Masque_Entropy#17
- [x] SFX-WoW/Masque_Gears#16
- [x] SFX-WoW/Masque_LiteStep#16
- [x] SFX-WoW/Masque_Serenity#17
